services:
  whisper-stt:
    ports:
      - 8881:8000
    image: ghcr.io/speaches-ai/speaches:latest-cuda-12.6.3
    volumes:
      - ./model_aliases.turbo.json:/home/ubuntu/speaches/model_aliases.json
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  kokoro-tts:
    ports:
      - 8882:8880
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.1
    environment:
      - DOWNLOAD_MODEL=true
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8880/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  indextts1.5:
    ports:
      - 8882:8000
    image: adriabama06/auto-video-translator-indextts1.5:latest
    build:
      context: util
      dockerfile: Dockerfile.indextts.1.5
    volumes:
      - ./checkpoints:/app/checkpoints
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  fish-speech:
    environment:
      - HF_TOKEN=your_token_here
    ports:
      - 8882:6673
    image: adriabama06/auto-video-translator-fish-speech:latest
    build:
      context: util
      dockerfile: Dockerfile.fish-speech
    volumes:
      - ./checkpoints:/opt/fish-speech/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  qwen3tts:
    ports:
      - 8882:8000
    image: adriabama06/auto-video-translator-qwen3tts:latest
    build:
      context: util
      dockerfile: Dockerfile.qwen3tts
    volumes:
      - ./checkpoints:/Qwen3-TTS/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  omnivoice:
    ports:
      - 8882:8001
    image: adriabama06/auto-video-translator-omnivoice:latest
    build:
      context: util
      dockerfile: Dockerfile.omnivoice
    volumes:
      - ./checkpoints:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  
  voxcpm2:
    ports:
      - 8882:8000
    image: vllm/vllm-omni:v0.22.0
    command: bash -c "pip install voxcpm && vllm serve openbmb/VoxCPM2 --omni --port 8000 --gpu-memory-utilization 0.7"
    ipc: host
    volumes:
      - ./checkpoints/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  higgsv3:
    ports:
      - 8882:8000
    # Use vllm/vllm-omni:v0.23.0 when it releases
    image: vllm/vllm-openai:v0.23.0
    command: -c "
      apt-get update
      && apt-get install -y git jq
      && apt-get clean
      && uv pip install --python \"$(python3 -c 'import sys; print(sys.executable)')\" --no-cache-dir git+https://github.com/vllm-project/vllm-omni.git@329c98ff9d9da37b8fa38bc3ea8005cb8472406f
      && curl 'https://raw.githubusercontent.com/vllm-project/vllm-omni/36a5e9cfd2e83d602fa83ca8d49b6534e37c604b/vllm_omni/deploy/higgs_multimodal_qwen3.yaml' -L -o higgs_multimodal_qwen3.yaml
      && vllm serve bosonai/higgs-audio-v3-tts-4b --quantization fp8 --max_model_len 8192 --deploy-config higgs_multimodal_qwen3.yaml --trust-remote-code --omni --port 8000 --gpu-memory-utilization 0.7
      "
    entrypoint: bash
    ipc: host
    volumes:
      - ./checkpoints/huggingface:/root/.cache/huggingface
    environment:
      - VLLM_USE_DEEP_GEMM=0
      - VLLM_MOE_USE_DEEP_GEMM=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  s2-pro:
    ports:
      - 8882:8000
    image: vllm/vllm-omni:v0.22.0
    command: bash -c "
      apt-get update
      && apt-get install -y git jq libportaudio2 portaudio19-dev
      && apt-get clean
      && uv pip install --python \"$(python3 -c 'import sys; print(sys.executable)')\" --no-cache-dir fish-speech
      && vllm serve fishaudio/s2-pro --quantization fp8 --max_model_len 2048 --deploy-config vllm-omni/vllm_omni/deploy/fish_qwen3_omni.yaml --omni --port 8000 --gpu-memory-utilization 0.8
      "
    ipc: host
    volumes:
      - ./checkpoints/huggingface:/root/.cache/huggingface
    environment:
      - VLLM_USE_DEEP_GEMM=0
      - VLLM_MOE_USE_DEEP_GEMM=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  libretranslate:
    image: libretranslate/libretranslate:v1.7.2-cuda
    ports:
      - "8883:5000"
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,es
    tty: true
    healthcheck:
      test: [ 'CMD-SHELL', './venv/bin/python scripts/healthcheck.py' ]
      interval: 10s
      timeout: 4s
      retries: 4
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
